replicaCount: 1
postgres:
  name: app-postgres
  group: db
  container:
    image: postgres:12.3
    port: 5432
  service:
    type: ClusterIP
    port: 5432
  volume:
    name: app-postgres-storage
    kind: PersistentVolumeClaim
    mountPath: /var/lib/postgresql/data
    pvc:
      name: app-postgres-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 4Gi
  config:
    name: app-postgres-config
    data:
      - key: POSTGRES_DB
        value: notes_app
      - key: POSTGRES_USER
        value: mapodoufu
      - key: POSTGRES_PASSWORD
        value: mapodoufu

