ingress:
  name: app-ingres
  hosts:
    - host: api.notes.biosave.org
      paths:
        - path: /
          backend:
            service:
              name: notes-app
              port:
                number: 8080