app:
  name: notes-app
  group: app
  replicaCount: 1
  container:
    image: added-here
    port: 8080
    config:
      - name: app-postgres-config
    env:
      - key: POSTGRES_HOST
        value: app-postgres
      - key: POSTGRES_PORT
        value: 5432
      - key: SERVER_PORT
        value: 8080
      - key: JWT_SECRET
        value: jwtmapodoufu
      - key: MIGRATIONS_PATH
        value: /app/migrations
      - key: APP_MODE
        value: Prod
  service:
    type: ClusterIP
    port: 8080
