app:
  name: notes-app
  group: app
  replicaCount: 1
  container:
    image: add-your-image-here
    port: 8080
    config:
      - name: app-postgres-config
    env:
      - name: POSTGRES_HOST
        value: app-postgres
      - name: POSTGRES_PORT
        value: 5432
      - name: SERVER_PORT
        value: 8080
      - name: JWT_SECRET
        value: jwtmapodoufu
      - name: MIGRATIONS_PATH
        value: /app/migrations
      - name: APP_MODE
        value: Prod
  service:
    type: ClusterIP
    port: 8080
